---
title: kerasgenerator v0.0.1 Released!
author: R. Dimas Bagas Herlambang
date: 2019-01-01 11:56:00 +7000
draft: no
slug: kerasgenerator-v0-0-1-released
categories:
  - R
tags:
  - kerasgenerator
  - package
  - R
image:
  caption: ''
  focal_point: ''
  preview_only: true
output:
  blogdown::html_page:
    toc: false
---

`kerasgenerator` package is designed to simplify the process of preparing the dataset so it could be properly passed to [`keras`](https://keras.rstudio.com){target="_blank"}' fit, evaluate, or predict on generator functions.

Currently, it is still in a very early development stage--it is even only have 2 functions right now :grin:. But it is my first experience in developing a package, and I really can't resist to publish it to test some features from [`devtools`](https://devtools.r-lib.org/){target="_blank"}, [`usethis`](https://usethis.r-lib.org/){target="_blank"}, and [`pkgdown`](https://pkgdown.r-lib.org/){target="_blank"}. To be honest, this is also one of the main reason I started this blog--which give me a perfect excuse to try [`blogdown`](https://github.com/rstudio/blogdown){target="_blank"}. I will share some of my experiences in using those package in this blog :smile:

At the moment I'm posting this, I'm still building some vignettes for `kerasgenerator`. As soon as it this finished, I will upload the link in the package website. I'm also developing some other features:

- Support for generating data from **file in specified path**
- Support for incorporating [`recipes`](https://tidymodels.github.io/recipes/){target="_blank"} package for **data preprocessing**
- Data generator for **k-shot learning** model fitting

If you interested in the package, please stay tuned on this blog for further post related to this package. Also don't forget to check the package's [website](https://kerasgenerator.bagasbgy.com/){target="_blank"} and push the star buttons on the package [GitHub repository](https://github.com/bagasbgy/kerasgenerator/){target="_blank"} :grin:

Happy new year!
